import json, base64

from bloodyAD.exceptions import LOG
from bloodyAD.network.ldap import Change


async def object(conn, target: str, backup_file: str):
    """
    Restore an attribute to its backed up value from a backup file

    :param target: sAMAccountName, DN or SID of the target
    :param backup_file: path to the .bak backup file generated by set object
    """
    with open(backup_file, "r") as f:
        backup_data = json.load(f)

    attribute = backup_data["attribute"]
    raw_values = [base64.b64decode(val) for val in backup_data["values"]]

    ldap = await conn.getLdap()
    await ldap.bloodymodify(
        target, {attribute: [(Change.REPLACE.value, raw_values)]}, encode=False
    )
    LOG.info(f"{target}'s {attribute} has been restored from {backup_file}")
